version: '2'
services:
          mysql:
                  container_name: erasmus_mysql
                  restart: always
                  image: mysql:5.6
                  ports:
                          - "3306:3306"
                  environment:
                          MYSQL_ROOT_PASSWORD: 'ROOT'
                          MYSQL_USER: 'erasmus'
                          MYSQL_PASS: 'erasmus'
                  volumes:
                   - erasmus-datavolume:/var/lib/mysql
volumes:
        erasmus-datavolume: {}
